from lightbulb.errors import LightbulbError
class RocketBotException(LightbulbError):
  def __init__(self, message: str, *args):
    self.message = message
    super.__init__(*args)

class GuildExistsError(RocketBotException): ...
class GuildNotFoundError(RocketBotException): ...
class UserNotFoundError(RocketBotException): ...