from lightbulb.errors import LightbulbError
class RocketBotException(LightbulbError):
  def __init__(message: str, *args):
    super(args)

class GuildExistsError(RocketBotException): ...
class GuildNotFoundError(RocketBotException): ...
class UserNotFoundError(RocketBotException): ...